package dev.ctrlspace.gendox.gendoxcoreapi.ai.engine.model.dtos.openai.response;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
public class Usage {
    // Core token counts from the AI provider
    @JsonProperty("prompt_tokens")
    private Integer promptTokens; // Input tokens sent to the model
    @JsonProperty("completion_tokens")
    private Integer completionTokens; // Output tokens generated by the model
    /**
     * OpenAI: {@code total_tokens = prompt_tokens + completion_tokens} (see API usage object).
     * For reasoning models, {@code completion_tokens} already includes reasoning; {@code
     * completion_tokens_details.reasoning_tokens} is a subset for visibility, not an extra add-on
     * to {@code total_tokens}. Other providers may differ when values are synthesized locally.
     */
    @JsonProperty("total_tokens")
    private Integer totalTokens;
    
    // Detailed breakdowns of token usage (provider-specific)
    @JsonProperty("prompt_tokens_details")
    private PromptTokensDetail promptTokensDetail; // e.g., cached, audio tokens for input
    @JsonProperty("completion_tokens_details")
    private CompletionTokensDetails completionTokensDetail; // e.g., reasoning tokens for o1 models


    @Data
    @Builder(toBuilder = true)
    @AllArgsConstructor
    @NoArgsConstructor
    public static class PromptTokensDetail {
        /**
         * Tokens served from the provider's prompt cache on this request.
         * OpenAI: {@code cached_tokens}. Anthropic: mapped from {@code cache_read_input_tokens}.
         */
        @JsonProperty("cached_tokens")
        private Integer cachedTokens;
        @JsonProperty("audio_tokens")
        private Integer audioTokens;
        /**
         * Anthropic: total input tokens written to the prompt cache on this request.
         * OpenAI responses omit this; remains null for OpenAI.
         */
        @JsonProperty("cache_creation_input_tokens")
        private Integer cacheCreationInputTokens;
        /**
         * Anthropic: breakdown of cache writes by TTL (5m default vs 1h extended).
         */
        @JsonProperty("cache_creation")
        private PromptCacheCreation cacheCreation;

        @Data
        @Builder(toBuilder = true)
        @AllArgsConstructor
        @NoArgsConstructor
        public static class PromptCacheCreation {
            @JsonProperty("ephemeral_5m_input_tokens")
            private Integer ephemeral5mInputTokens;
            @JsonProperty("ephemeral_1h_input_tokens")
            private Integer ephemeral1hInputTokens;
        }
    }

    @Data
    @Builder(toBuilder = true)
    @AllArgsConstructor
    @NoArgsConstructor
    public static class CompletionTokensDetails {
        @JsonProperty("reasoning_tokens")
        private Integer reasoningTokens;
        @JsonProperty("audio_tokens")
        private Integer audioTokens;
        @JsonProperty("accepted_prediction_tokens")
        private Integer acceptedPredictionTokens;
        @JsonProperty("rejected_prediction_tokens")
        private Integer rejectedPredictionTokens;
    }
}
