#version: '3.9'

services:
  keycloak:
    build:
      context: .  # Use the Dockerfile in the current directory
    image: custom-keycloak:25.0.4
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - 8080:8080
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    volumes:
      - ./themes:/opt/keycloak/themes  # Optional: Mount your custom themes
    restart: unless-stopped
    networks:
      - keycloak_network

  postgres_keycloak:
    image: postgres:13
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: ${KC_DB_URL_DATABASE}
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    healthcheck:
      test: "exit 0"
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - keycloak_network

volumes:
  postgres_data:

networks:
    keycloak_network:
        driver: bridge
