

server:
  port: 8080
  servlet:
    context-path: /gendox/api/v1
logging:
  level:
    dev.ctrlspace: DEBUG
    org.springframework: INFO
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5

gendox:
  domains:
    frontend: https://dev.gendox.ctrlspace.dev
  documents:
    upload-dir: file:${user.home}/gendox/documents
    wordCount: 300
    allowed:
      extensions: .txt,.md,.rst,.pdf

  integrations:
#    poller: 120000 # 90 seconds
    #    poller: 300000
    poller: 86400000 # 24 hours in milliseconds
    storage:
      temporary: file:${user.home}\\gendox\\temporary_integration_files
    #      temporary: s3://gendox.organization.documents.local/gendox_wiki
    s3:
      sqs:
        wait-time-seconds: 1 #not in use
        visibility-timeout-seconds: 300


proven-ai:
  base-url: https://dev.proven-ai.ctrlspace.dev


#ISCC Code
iscc:
  apis:
    code-generation: https://proven-ai-dev.ctrlspace.dev/api/v1/iscc