

server:
  port: 8080
  servlet:
    context-path: /gendox/api/v1
logging:
  level:
    dev.ctrlspace: DEBUG
    org.springframework: INFO
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

gendox:
  domains:
    frontend: https://dev.gendox.ctrlspace.dev


proven-ai:
  base-url: https://dev.proven-ai.ctrlspace.dev


#ISCC Code
iscc:
  apis:
    code-generation: https://proven-ai-dev.ctrlspace.dev/api/v1/iscc