version: '3.7'

services:
  gendox-keycloak:
    build:
      context: ../../gendox-keycloak
      dockerfile: Dockerfile
    image: gendox-keycloak:latest
    container_name: gendox-keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - KEYCLOAK_HTTP_RELATIVE_PATH=${KEYCLOAK_HTTP_RELATIVE_PATH}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT}
    entrypoint: ["/bin/bash", "/opt/keycloak/entrypoint.sh"]
    ports:
      - "8443:8443"
    volumes:
      - keycloak-data:/opt/keycloak/conf
    restart: unless-stopped

volumes:
  keycloak-data:
